server:
  error:
    include-stacktrace: always
    include-exception: on
    include-message: always
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 759254302934-h0u67i38q8idqkvvjr5v0dmfmni59a0m.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000
            scope:
              - email
              - profile
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  main:
    web-application-type: reactive
  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS:14.225.205.235}
    port: ${CASSANDRA_PORT:39042}
    keyspace-name: ${CASSANDRA_KEYSPACE_NAME:dyson_blog_local}
    username: ${CASSANDRA_USERNAME:cassandra}
    password: ${CASSANDRA_PASSWORD:P@ssword789}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: create_if_not_exists
  data:
    web:
      pageable:
        default-page-size: 20
logging:
  level:
    org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate: debug
    org.dyson.blog: debug
    org.springframework.security: trace
    org.springframework.web: trace
#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html
#  api-docs:
#    path: /api-docs
#  show-actuator: false
#  show-login-endpoint: true
#  show-oauth2-endpoints: true
#  swagger-ui:
#    operations-sorter: alpha
#    tags-sorter: alpha
#    config-url: ${server.path}/api-docs/swagger-config
#    url: ${server.path}/api-docs
#    disable-swagger-default-url: true
#    oauth2-redirect-url: ${server.path}/swagger-ui/oauth2-redirect.html
#  server-urls:
#    - ${server.path}
#    - ${application.domain.server}
